main:
  - name: About
    url: /
    weight: 10
  - name: Research
    url: /#research
    weight: 20
  - name: Publications
    url: /#papers
    weight: 30
  - name: Background
    url: /experience/
    weight: 40
